export const ACCOUNT_FORM_NAME = 'account'
export const LOGIN_FORM_NAME = 'login'
export const SIGNUP_FORM_NAME = 'signup'
export const NEW_PROJECT_FORM_NAME = 'newProject'
export const NEW_POST_FORM_NAME = 'newPost'
export const NEW_ANSWER_FORM_NAME = 'newAnswer'
